basePath: /api
definitions:
  main.Response:
    properties:
      data: {}
      errors:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  description: Go server for MVP app
  title: Swagger MVP API
  version: "1.0"
paths:
  /api/health:
    get:
      consumes:
      - application/json
      description: Health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
      summary: Health check
      tags:
      - health
  /api/recipe:
    post:
      consumes:
      - application/json
      description: generate recipe
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              allOf:
              - $ref: '#/definitions/main.Response'
              - properties:
                  data:
                    items:
                      type: string
                    type: array
                type: object
            type: array
      summary: Generate recipe
      tags:
      - recipe
swagger: "2.0"
