name: "Unit Tests"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...    
        working-directory: ./server
      - name: go-test-coverage
        uses: vladopajic/go-test-coverage@v2.11.2
        with:
          config: ./.testcoverage.yml
